" TODO figure out 80 char auto return
" utf8 so epic
set encoding=utf-8

" Show line numbers
set number         " line nums
set relativenumber " relavive line nums

" Status bar always showing
set laststatus=2

" Highlight
syntax on

" indent
set noexpandtab    " tabs are tabs
filetype indent on " indenting based on file extensions
set autoindent     " keeps indent the same for settings
set shiftwidth=4   " indents 4 chars
set tabstop=4      " ^

" no file safety
set nobackup   " no backup files

" scroll buffer distance
set scrolloff=8

" searching
set incsearch " gradually show search as typed
set hlsearch  " highlight search matches

set nowrap " no linewrap

" search
set ignorecase " ignore case during search...
set smartcase  " ...unless you actually use a cap

" show last cmd typed on bottom
set showcmd

" show mode always
set showmode

" show vim command history
set history=1000
