" TODO figure out 80 char auto return
" utf8 so epic
set encoding=utf-8

" Show line numbers
set number
set relativenumber

" Status bar always showing
set laststatus=2

" Highlight
syntax on

" indent
set noexpandtab    " tabs are tabs
filetype indent on " indenting based on file extensions
set autoindent     " keeps indent the same for settings
set shiftwidth=4   " indents 4 chars
set tabstop=4      " ^

" Don't make lame backup files
set nobackup

" scroll buffer distance
set scrolloff=8

" highlight while writing
set incsearch
set hlsearch

" no linewrap 
set nowrap

" ignore case during search
set ignorecase
set smartcase

" show last cmd typed on bottom
set showcmd

" show mode always
set showmode

" show vim command history
set history=1000
