#!/bin/sh -eu

# colors
alias ls="ls --color=auto -F"
alias tree="tree -C"
alias grep="grep --color=auto"

alias rm="rm -iv"
alias shred="shred -v"
alias cal="cal -m"
alias ping="ping -c 3"
alias cp="cp -v"
alias mv="mv -iv"
alias mkdir="mkdir -v"
alias rmdir="rmdir -v"

alias zshrc="$EDITOR ${ZDOTDIR:-${HOME}}/.zshrc && source ${ZDOTDIR:-${HOME}}/.zshrc"
alias aliasrc="$EDITOR $XDG_CONFIG_HOME/shell/aliasrc && source ${ZDOTDIR:-${HOME}}/.zshrc"
[ -x "$(command -v doas)" ] && alias sudo='doas'

# mailsync stuff
[ -f "$MBSYNCRC" ] && alias mbsync="mbsync -c $MBSYNCRC"

# calcs
alias bc="bc -q"
if dc --help 2>&1 | grep -iq gnu && [ -f "$DCRC" ]; then
	alias dc="dc -f $DCRC -"
fi

# abook
alias abook="abook --config '$XDG_CONFIG_HOME/abook/abookrc' --datafile '$XDG_DATA_HOME/abook/addressbook'"

# colored ssh w/ foot
if [ "$TERM" = "foot" ]; then
	alias ssh='TERM=xterm-256color ssh'
fi
